#image: "php:7.4-apache-buster"
image: "registry.gitlab.com/fapariciorteam/ddd-symfony4-boilerplate:latest"

# Cache libraries in between jobs
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - vendor/
        - bin
        - var
        - node_modules

before_script:
    - apt -y update
    - a2enmod rewrite
#    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
#    - php composer-setup.php
#    - php -r "unlink('composer-setup.php');"
#    - mv composer.phar /usr/local/bin/composer
#    - curl -sS https://get.symfony.com/cli/installer | bash
#    - mv /root/.symfony/bin/symfony /usr/local/bin
#    - apt -y install git libzip-dev unzip
#    - docker-php-ext-install zip
#    - pecl install xdebug-2.9.4
#    - echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini
#    - echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini
#    - echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini
#    - apt -y install nodejs npm
#    - npm install npm@latest -g
#    - apt -y install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

build php:
    stage: build
    script: sh ./.gitlabci/build.sh
    rules:
        - if: $CI_COMMIT_BRANCH == 'master'   # Execute jobs when a new commit is pushed to master branch
        - if: $CI_MERGE_REQUEST_ID

build javascript:
    stage: build
    script: npm install
    rules:
        - if: $CI_COMMIT_BRANCH == 'master'   # Execute jobs when a new commit is pushed to master branch
        - if: $CI_MERGE_REQUEST_ID

unit test:
    stage: test
    script: sh ./.gitlabci/unit-test.sh
    rules:
        - if: $CI_COMMIT_BRANCH == 'master'   # Execute jobs when a new commit is pushed to master branch
        - if: $CI_MERGE_REQUEST_ID
    artifacts:
        paths:
            - build
            - doc/hugo/public
        expire_in: 1 hour

functional test:
    stage: test
    script: sh ./.gitlabci/functional-test.sh
    rules:
        - if: $CI_COMMIT_BRANCH == 'master'   # Execute jobs when a new commit is pushed to master branch
        - if: $CI_MERGE_REQUEST_ID
    artifacts:
        paths:
            - cypress/videos
            - cypress/screenshots
            - cypress/reports/mochareports
        when: always
        expire_in: 1 hour
    after_script:
        - npm run posttest

pages:
    before_script:
        - echo "Do nothing in this stage"
    stage: deploy
    dependencies:
        - unit test
        - functional test
    script:
        - bash ./.gitlabci/deploy-pages.sh
    artifacts:
        paths:
            - public
        expire_in: 1 day
    only:
        - master
