image: "php:7.4-apache-buster"

before_script:
    - apt -y update
    - a2enmod rewrite
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - mv composer.phar /usr/local/bin/composer
    - curl -sS https://get.symfony.com/cli/installer | bash
    - mv /root/.symfony/bin/symfony /usr/local/bin
#    - groupadd -r devel -g 1000
#    - useradd --no-log-init -u 1000 -r -g devel devel
    - apt -y install git libzip-dev
    - docker-php-ext-install zip
    - pecl install xdebug-2.9.4
    - echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini
    - echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini
    - echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini

build:
    stage: build
    script: ./gitlabci/build
    rules:
        -   if: $CI_COMMIT_BRANCH == 'master'   # Execute jobs when a new commit is pushed to master branch
        -   if: $CI_MERGE_REQUEST_ID
