build:
    environment:
        php:
            version: "7.3.1"
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true

        coverage:
            tests:
                override:
                    - command: bin/console --env=behat doctrine:database:create
                    - command: bin/console --env=behat doctrine:migrations:migrate --no-interaction
                    - command: ./bin/simple-phpunit --config phpunit.xml --coverage-html build/coverage-report --log-junit build/junit.xml --coverage-clover build/clover.xml
                      coverage:
                          file: build/clover.xml   # <- Set this to where we find the coverage data.
                          #    The path is relative to the current directory.
                          format: clover
                    - command: 'APP_ENV=behat bin/behat'
    tests:
        override:
            - true

filter:
    excluded_paths:
        - 'tests/*'
        - 'bin/*'
        - 'features/*'
        - 'src/Shared/Infrastructure/Symfony/Kernel.php'

checks:
    php: true

tools:
    #    external_code_coverage: true
    php_code_coverage: true
    php_sim: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    php_cpd: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cs_fixer:
        config: { level: psr2 }