version: "3"

services:
    web:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        image: webapp_php
        container_name: webapp_php
        volumes:
            - ./:/var/www/html
        ports:
            - "80:80"
            - "8000:8000"
        networks:
            - webnet

#        env_file:
#            - .env

networks:
    webnet:
