version: "3"

services:
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        image: webapp_php
        container_name: webapp_php
        sysctls:
            - net.ipv4.ip_unprivileged_port_start=0
        volumes:
            - ./:/var/www/html
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - webnet

    apache:
        build:
            context: ./docker/apache
            dockerfile: Dockerfile
        image: webapp_apache
        container_name: webapp_apache
        volumes:
            - ./:/usr/local/apache2/htdocs/
            - ./docker/apache/my-httpd.conf:/usr/local/apache2/conf/httpd.conf
        ports:
            - "80:80"
            - "8000:8000"
        networks:
            - webnet
        links:
          - php
    node:
        build:
            context: ./docker/node
            dockerfile: Dockerfile
        image: webapp_node
        container_name: webapp_node
        working_dir: /var/www/html
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/var/www/html
        networks:
            - webnet
        depends_on:
          - apache

networks:
    webnet:
