version: "3"

services:
    web:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        image: webapp_php
        container_name: webapp_php
        volumes:
            - ./:/var/www/html
        ports:
            - "80:80"
            - "8000:8000"
        networks:
            - webnet

    node:
        build:
            context: ./docker/node
            dockerfile: Dockerfile
        image: webapp_node
        container_name: webapp_node
        working_dir: /var/www/html
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/var/www/html
        networks:
            - webnet
        depends_on:
          - web
#    selenium-chrome:
#        image: selenium/standalone-chrome
#        ports:
#            - "4444:4444"
#        volumes:
#            - /dev/shm:/dev/shm
#        networks:
#            - webnet

#        env_file:
#            - .env

networks:
    webnet:
