# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

jobs:
    build:
        docker:
            # Specify the version you desire here
            - image: circleci/php:7.4

        steps:
            - checkout

            - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
            - run: sudo docker-php-ext-install zip

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      # "composer.lock" can be used if it is committed to the repo
                      - v1-dependencies-{{ checksum "composer.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: composer install -n --prefer-dist

            - run: composer require --dev php-coveralls/php-coveralls

            - save_cache:
                  key: v1-dependencies-{{ checksum "composer.json" }}
                  paths:
                      - ./vendor

            # prepare the database
            - run: bin/console --env=behat doctrine:database:create
            - run: bin/console --env=behat doctrine:migrations:migrate --no-interaction

            # run tests with phpunit or codecept
            - run: ./bin/simple-phpunit --config phpunit.xml --coverage-html build/coverage-report --log-junit build/junit.xml --coverage-clover build/clover.xml
            - run: APP_ENV=behat bin/behat

            - run: ./bin/php-coveralls
            - run: bash <(curl -s https://codecov.io/bash)

            - store_test_results:
                path: ~/project/build

            - store_artifacts:
                path: build/coverage-report
            - store_artifacts:
                path: build/junit.xml
            - store_artifacts:
                path: build/clover.xml