App\Users\User\Domain\User:
    type: entity
    table: user
    repositoryClass: App\Users\User\Infrastructure\Persistence\DoctrineUserRepository
    id:
        userId:
            type: guid

    fields:
        username:
            type: string
        password:
            type: string
        email:
            type: string

