services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Users\User\Ui\:
        resource: '../../../Ui/*'
        tags: ['controller.service_arguments']

    App\Users\User\Application\SignUpUser\SignUpUserCommandHandler:
        tags:
        - { name: tactician.handler, command: App\Users\User\Application\SignUpUser\SignUpUserCommand }

    App\Users\User\Domain\Specifications\UserSpecificationChain:
        factory: ['App\Users\User\Domain\Specifications\UserSpecificationChain', 'build']


    App\Users\User\Domain\Specifications\:
        resource: '../../../Domain/Specifications/*'

    App\Users\User\Domain\UserRepositoryInterface:
        alias: App\Users\User\Infrastructure\Persistence\InMemoryUserRepository

    App\Users\User\Infrastructure\Persistence\:
        resource: '../../../Infrastructure/Persistence/*'
