services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Users\User\Ui\:
        resource: '../../../Ui/'
        tags: ['controller.service_arguments']

    App\Users\User\Application\SignUpUser\SignUpUserCommandHandler:
        tags:
        - { name: tactician.handler, command: App\Users\User\Application\SignUpUser\SignUpUserCommand }

    App\Users\User\Application\DeleteUser\DeleteUserCommandHandler:
        tags:
        - { name: tactician.handler, command: App\Users\User\Application\DeleteUser\DeleteUserCommand }

    App\Users\User\Domain\Specifications\UserSpecificationChain:
        factory: ['App\Users\User\Domain\Specifications\UserSpecificationChain', 'build']
        arguments:
            - '@App\Users\User\Domain\Specifications\UserEmailIsUnique'
            - '@App\Users\User\Domain\Specifications\UserNameIsUnique'
            - '@App\Users\User\Domain\Specifications\UserIdIsUnique'

    App\Users\User\Domain\Specifications\UserIdIsUnique:
        factory: ['App\Users\User\Domain\Specifications\UserIdIsUnique', 'build']
        class: App\Users\User\Domain\Specifications\UserIdIsUnique

    App\Users\User\Domain\Specifications\UserEmailIsUnique:
        factory: ['App\Users\User\Domain\Specifications\UserEmailIsUnique', 'build']
        class: App\Users\User\Domain\Specifications\UserEmailIsUnique

    App\Users\User\Domain\Specifications\UserNameIsUnique:
        factory: ['App\Users\User\Domain\Specifications\UserNameIsUnique', 'build']
        class: App\Users\User\Domain\Specifications\UserNameIsUnique

    App\Users\User\Domain\Specifications\:
        resource: '../../../Domain/Specifications/'

    App\Users\User\Domain\UserRepositoryInterface:
        alias: App\Users\User\Infrastructure\Persistence\InMemoryUserRepository

    App\Users\User\Infrastructure\Persistence\:
        resource: '../../../Infrastructure/Persistence/'
