services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Behat\DemoContext:
        public: true
        arguments:
            - "@kernel"
            - "%kernel.environment%"