imports:
    - { resource: ../src/Shared/Infrastructure/Symfony/config/services_test.yaml}

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Behat\BehatTestEnvironmentContext:
        public: true
        arguments:
            - "@kernel"
            - "%kernel.environment%"