#!/usr/bin/env php

<?php

echo "Running tests.. ";

exec('docker ps | grep webapp_php | wc -l', $output, $returnCode);

if ($returnCode === 0) {
    if($output[0] === "1") {
        exec('docker-compose exec php "bin/simple-phpunit"', $output, $returnCode);
    } else {
        exec('docker-compose run php "bin/simple-phpunit"', $output, $returnCode);
    }
}

if ($returnCode !== 0) {
  // Show full output
  echo PHP_EOL . implode($output, PHP_EOL) . PHP_EOL;
  echo "Aborting commit.." . PHP_EOL;
  exit(1);
}

// Show summary (last line)
echo array_pop($output) . PHP_EOL;
exit(0);
