services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Shared\Infrastructure\Service\UniqueIdProviderInterface:
        alias: App\Shared\Infrastructure\Service\UniqueIdProvider

    App\Shared\Infrastructure\Service\UniqueIdProvider:
        class: App\Shared\Infrastructure\Service\UniqueIdProvider

    Ramsey\Uuid\UuidFactory:
        class: Ramsey\Uuid\UuidFactory
