doctrine:
    dbal:
        types:
            User_UserId: App\Users\User\Infrastructure\Persistence\Mappings\Types\UserIdType
            User_UserName: App\Users\User\Infrastructure\Persistence\Mappings\Types\UserNameType
            User_Email: App\Users\User\Infrastructure\Persistence\Mappings\Types\EmailType
            User_Password: App\Users\User\Infrastructure\Persistence\Mappings\Types\PasswordType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Users/User/Infrastructure/Persistence/Mappings'
                prefix: 'App\Users\User\Domain'
                alias: User
