doctrine:

#    dbal:
#        types:
#            userId: App\Users\User\Domain\ValueObjects\UserId

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Users/User/Infrastructure/Persistence/Mappings'
                prefix: 'App\Users\User\Domain'
                alias: User
